name: Python App CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # workflow_dispatch:
  #   inputs:
  #     environment:
  #       description: 'Please, select an environment to run against:'
  #       type: environment
  #       required: true

env:
  REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  IMAGE_NAME: ${{ vars.APP }}

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Bump Version Tag
      id: tag_version
      uses: anothrNick/github-tag-action@1.64.0
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_PAT }}
        WITH_V: true
        DEFAULT_BUMP: patch
        INITIAL_VERSION: 1.0.0

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_REGISTRY }}
        password: ${{ secrets.DOCKER_PAT }}

    - name: Build & Push
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag_version.outputs.new_tag }}"
        push: true

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        environment: ['dev', 'qa', 'prd']

    environment:
      name: ${{ matrix.environment }}
    
    steps:
    - name: Deployment
      run: echo "Deploying to ${{ matrix.environment }}"
