name: Python App Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    - name: Build & Push
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
      run: |
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        echo ${{ secrets.DOCKER_PAT }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
        docker build . --file Dockerfile --tag "${{ secrets.DOCKER_USER }}/pythonapp:$(git_hash)"
        docker push "${{ secrets.DOCKER_USER }}/pythonapp:$(git_hash)"
