name: P-UNIT-PROJECT-CI-MICROSERVICE

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  compliance:
    name: Compliance
    uses: gitdsoares/templates/.github/workflows/compliance.yml@main
    permissions: write-all
    with:
      APP_NAME: ${{ vars.APP_NAME }}
    secrets:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      DOCKER_PAT: ${{ secrets.DOCKER_PAT }}

  build:
    name: Build
    uses: gitdsoares/templates/.github/workflows/build.yml@main
    needs: compliance
    permissions: write-all
    with:
      APP_NAME: ${{ vars.APP_NAME }}
    secrets:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      DOCKER_PAT: ${{ secrets.DOCKER_PAT }}  