name: P-UNIT-PROJECT-MICROSERVICE

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - closed
    branches:
      - main

env:
  REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  IMAGE_NAME: ${{ vars.APP }}

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Bump Version Tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_PAT }}
          WITH_V: true
          DEFAULT_BUMP: patch
          INITIAL_VERSION: 1.0.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag_version.outputs.new_tag }}"
          push: true

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "docker.io/${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag_version.outputs.new_tag }}"
          format: sarif
          output: trivy-results.sarif

      - name: Publish Trivy Report
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: trivy-results.sarif

  dev:
    name: DEV
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: dev 
    steps:
      - name: Deployment
        run: echo "Deploying to dev"

  qa:
    name: QA
    runs-on: ubuntu-latest
    needs: dev
    environment:
      name: qa 
    steps:
      - name: Deployment
        run: echo "Deploying to qa"

  prd:
    name: PRD
    runs-on: ubuntu-latest
    needs: qa
    environment:
      name: prd
    steps:
      - name: Deployment
        run: echo "Deploying to prd"