name: P-UNIT-PROJECT-CI-MICROSERVICE

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - closed
    branches:
      - main
  
  workflow_dispatch:

jobs:
  compliance:
    name: Compliance
    uses: gitdsoares/templates/.github/workflows/compliance.yml@main
    permissions: write-all
    with:
      APP_NAME: ${{ vars.APP }}
    secrets:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      DOCKER_PAT: ${{ secrets.DOCKER_PAT }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: compliance
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump Version Tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_PAT }}
          WITH_V: true
          DEFAULT_BUMP: patch
          INITIAL_VERSION: 1.0.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build & Push
        id: build_push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: "${{ secrets.DOCKER_REGISTRY }}/${{ vars.APP }}:${{ steps.tag_version.outputs.new_tag }}"
          push: true

    outputs:
      IMAGE_TAG: ${{ steps.tag_version.outputs.new_tag }}